### ISSUE TITLE
Is it possible to develop such a node

### ISSUE THREAD

**Issue by BoosterCore** [YOUR-WORST-TACO/ComfyUI-TacoNodes#2]
Hello, I noticed that the current Img2Img Loader node cannot receive other nodes to input image for it.Even if I convert the image to the input it cannot accept the connection.
This is slightly inconvenient. Imagine that there is such an application scenario. I generate an image in a normal way and want to immediately and automatically pass it to the Img2Img Loader node for animation generation. So, is it possible to add an Img2Img Loader node with an image input port?

**Comment by YOUR-WORST-TACO** [comment]
Its funny, I thought about this yesterday, I can make that happen.

**Comment by YOUR-WORST-TACO** [comment]
Ask and ye shall receive: 

[Img2ImgAnimatedProcessor](https://github.com/YOUR-WORST-TACO/ComfyUI-TacoNodes/tree/main#taco-img2img-animated-processor)

**Comment by BoosterCore** [comment]
That’s cool. Thank you so much. I’ve tested it and it’s perfect!
https://youtu.be/pXI-6asyyFU?si=Xo-9o6dSRLP7RUfW
