### ISSUE TITLE
scale to side node

### ISSUE THREAD

**Issue by Ragamuffin20** [YOUR-WORST-TACO/ComfyUI-TacoNodes#3]
not really an issue but were are you getting the scale to side node?

**Comment by YOUR-WORST-TACO** [comment]
those are coming from this package: https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes

It mostly contains the scaling nodes, I have not personally used any of the other nodes

**Comment by Ragamuffin20** [comment]
> those are coming from this package: https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes
> 
> It mostly contains the scaling nodes, I have not personally used any of the other nodes

thanks
